### ISSUE TITLE
[Add request] many fake domains

### ISSUE THREAD

**Issue by JobcenterTycoon** [blocklistproject/Lists#588] opened 2021-12-09 22:59 UTC
URL you wish to be added:

<details>

```
procrackerz.org
freeprosoftz.com
pccrackbox.com
365crack.com
pclicensekeys.com
cracklabel.com
keystool.com
aglianicodelvulture.eu
pcwarezbox.com
installcracks.com
10crack.com
licensekey4u.co
reallcrack.com
hit4crack.com
crackproductkey.com
profullversion.com
vcracks.com
keysfull.net
naqeebicrack.com
allcracks.org
crackswall.com
crackthere.com
crackpcsoft.net
a2zp30.net
crackserialkey.co
keygenfile.net
alicracks.com
maliksofts.com
proappcrack.com
flstudiocrack.org
scracked.com
crackpropc.com
crackwinz.com
cyberspc.com
crackedpcs.com
softzcrack.com
ayeshapc.com
crackshome.org
crackintopc.com
crackzoo.net
crackhomes.com
zslicensekey.com
cracksmad.com
iamactivator.com
crackproduct.com
excrack.com
mahcrack.com
get4pcs.com
genuineactivator.com
keygenwin.com
thiscrack.com
crackedroot.com
crackspro.co
topcracked.com
mycrackfree.com
cracksoftwareguru.com
crackfullpro.com
starcrack.net
procrackpc.com
crackknow.com
cracxpro.com
crackpro.org
4howcrack.com
crackshere.com
crackdj.com
procrackpc.com
cracksray.com
crackkits.com
trycracksoftware.com
fullcrackedpc.com
cracktopc.com
filepapa.com
crackkey4u.com
cyberspc.com
rootcracks.org
getproductkey.co
idmfullcrack.info
fileserialkey.com
licensekeyup.com
thecrackbox.com
rootcracks.co
proactivationkey.com
cracksway.com
clevercracks.com
shahzifpc.com
idmpatched.com
getprocrack.co
allpcsoftcrack.co
autocracking.com
macwinsofts.com
productkeyfree.org
crackwatch.org
chcracked.com
cracksdat.com
patchcracks.com
activationkeys.co
serialsofts.com
piratpc.com
bulletcracks.com
prosoftlink.com
cracksole.com
finalcracked.com
activatorpros.com
organiccrack.com
zscracked.com
miraclecrack.com
abbaspc.org
allsoftwarekeys.com
genuineserials.com
pfcbwp.com
softwar2crack.com
xforce-cracks.com
procracks.net
productkeyforfree.com
crackgrid.com
licensekeysfree.com
goharpc.com
crackedmod.com
crackvip.com
crackedpc.org
activatorwin.com
whitecracked.com
softwarance.com
kalicrack.com
pcactivationkey.co
bypassapp.com
ziapc.org
zgamespc.com
cracksoon.com
boxcracked.com
procrackkey.co
activationkey.org
mjcracks.co
newproductkey.com
protoolscrack.net
download4mac.com
serialkeypatch.org

premiumsforum.com
profreefiles.com
fileprosoft.com
filespremium.com
newfreefiles.com
yfghfg.xyz
ujghjgf.xyz
gjfggj.xyz
hjygd6.xyz
gjhvjgh.xyz
rtrttf.xyz
```

</details>
Why you believe this should be added:

These sites looks like they provide "cracks" but its all fake, all download buttons redirect to virus download links. When you open a few it really gets clear, its all the same crap. VT reports:

```
https://www.virustotal.com/gui/file/0d10d10e68bfa8369b7f95dc5ed5fc6c9a2007047bbc67029cb630defc617355?nocache=1
https://www.virustotal.com/gui/file/792378e50318c49d8dd586c08a1961b38aec4cc96984898c9a054cc0693dd2a0?nocache=1
https://www.virustotal.com/gui/file/1d7a76cdbd2737ab5f232807136808843ea4c791aecf3eaa4214e467bf4ce74d
https://www.virustotal.com/gui/file/064b047644b71f7437833592347d5714e46e2977896c459cadeccd5aa993aa41?nocache=1
```

Add to list: abuse (The sites directly no provide malware, it trick the user to download their "cracks" (viruses) wich are on other sites
Other info you think we should know: These domains can be easily found wich a simple search like "camtasia crack". I checked and collected some domains

**Comment by spirillen** [comment] 2021-12-09 23:13
I don't think it will be rather useful to blacklist these "fish" sites, the real game will start if you could provide the destination sites, these front end will anyway be dead in 2 weeks

**Comment by JobcenterTycoon** [comment] 2021-12-09 23:17
No i reported it already a month ago to a other list https://github.com/RPiList/specials/issues/676 and many domains are still on the search results. I just added a few more domains for this issue

**Comment by iam-py-test** [comment] 2021-12-09 23:26
> No i reported it already a month ago to a other list [RPiList/specials#676](https://github.com/RPiList/specials/issues/676) and many domains are still on the search results. I just added a few more domains for this issue. I like this blocklist more thats why i report here
> 
> A few stable destination sites are already listed at the bottom. The final virus links are hosted on legit domains like discordcdn or aws.

Try reporting abuse to the regstrar or report to https://urlhaus.abuse.ch

**Comment by spirillen** [comment] 2021-12-09 23:26
Funny I thought you where French und nicht germanen.

Ok If you post them on mypdns I'll add them for you there. :+1:  I admit 146 domains is a bit and for which category should they be put into... Malicious?

**Comment by JobcenterTycoon** [comment] 2021-12-09 23:38
@iam-py-test i tried but the files are password protected so the automated Antivirus scan can't find anythink so nothing get added to the database. Or the URL rotating, when URLhaus try to confirm the URL already changed (like download1.exe to download2.exe). Manual reporting to the hoster is to time consuming, i already tried and the destination URL fast changing.

@spirillen yes

**Comment by iam-py-test** [comment] 2021-12-10 00:25
> @iam-py-test i tried but the files are password protected so the automated Antivirus scan can't find anythink so nothing get added to the database. Or the URL rotating, when URLhaus try to confirm the URL already changed (like download1.exe to download2.exe). Manual reporting to the hoster is to time consuming, i already tried and the destination URL fast changing. (mega.nz seems the best here, they react already after a few minutes)
> 

Yep - encountered that problem. I did blocklist all those domains for what it's worth

**Comment by JobcenterTycoon** [comment] 2021-12-10 14:23
what
<img width="717" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/145588658-dcc1884d-5fb6-42d7-a9e5-3932317aad0c.PNG">

**Comment by iam-py-test** [comment] 2021-12-10 14:24
> what? <img alt="Unbenannt" width="717" src="https://user-images.githubusercontent.com/48647394/145588658-dcc1884d-5fb6-42d7-a9e5-3932317aad0c.PNG">

Do you have a GL account?

**Comment by JobcenterTycoon** [comment] 2021-12-10 14:25
Yes

**Comment by iam-py-test** [comment] 2021-12-10 14:26
> Yes

Try just creating an account without linking it:
![image](https://user-images.githubusercontent.com/84232764/145589262-418f310c-637d-4fd9-9d20-f37bd5296773.png)

**Comment by JobcenterTycoon** [comment] 2021-12-10 15:07
When i try to post it says "Your issue has been recognized as spam and has been discarded."

**Comment by iam-py-test** [comment] 2021-12-10 15:07
> When i try to post it says "Your issue has been recognized as spam and has been discarded."

@spirillen please help

**Comment by spirillen** [comment] 2021-12-10 23:54
> When i try to post it says "Your issue has been recognized as spam and has been discarded."

It have been family dinner day, but that "spam" is one almost everyone receive once. You got three, but on't worry I've got 9 in total (as I have back up  accounts) but should be fixed now.

Thanks for this report, I will have to look at the config tomorrow as it is the intention you should be able to create "copy" you account directly with github/gitlab.

**Comment by spirillen** [comment] 2021-12-10 23:57
@iam-py-test did you have the same issues when you signed up at mypdns?

**Comment by iam-py-test** [comment] 2021-12-11 01:10
> @iam-py-test did you have the same issues when you signed up at mypdns?

I don’t think so. I didn’t try to reproduce because I didn’t want to spam with useless issues

**Comment by cryptogap** [comment] 2021-12-22 12:44
These have been added to abuse, thank you

**Closed by cryptogap** 2021-12-22 12:44 UTC
Labels: Add Request

**Comment by spirillen** [comment] 2021-12-27 16:27
The actual malware sites would be something like `10crack.com` = `` & `134.122.115.190`

![image](https://user-images.githubusercontent.com/44526987/147488738-427eb482-61eb-4231-aa7d-6c98b71b265c.png)

:thought_balloon: :thought_balloon:  :thinking:
