### ISSUE TITLE
[Edit request] Invalid URLs report

### ISSUE THREAD

**Issue by 1alessandro1** [blocklistproject/Lists#605] opened 2022-01-04 12:14 UTC
URL you wish to be checked:

```
  [i] Target: https://blocklistproject.github.io/Lists/phishing.txt
  [✓] Status: No changes detected
  [i] Analyzed 190229 domains, 7 domains invalid!
      Sample of invalid domains:
      - госулуги.рф
      - госуслуги-ру.рф
      - гослуги.рф
      - госсуслуга.рф
      - госсуслуугии.рф
```

Why you believe this should be checked:

 Because there are errors reported by pi-hole

**Comment by n0svc** [comment] 2022-01-16 19:27
Just a bit of info. Take it or trash it. It may be too much hassle to bother with.

The problem is characters that pi-hole doesn't support. If it is not to hard or does not cause problems with other uses the offending domains (with invalid characters) could be changed to punycode.

example  "#' is invalid domain followed by punycode (accepted by pi-hole)
```
# госулуги.рф
xn--c1aapkosob.xn--p1ai
# госуслуги-ру.рф
xn----etbaunrsdatce.xn--p1ai
# гослуги.рф
xn--c1aapkosp.xn--p1ai
# госсуслуга.рф
xn--80afa5aosaarc.xn--p1ai
# госсуслуугии.рф
xn--c1aapamrvaatca.xn--p1ai
# госуспуги.рф
xn--c1aapwflapc.xn--p1ai
# госуслуги-госномера.рф
xn----8sbhabmswnjffb4aeag2ac.xn--p1ai
```

It would be nice if pi-hole would covert it automatically, but I guess not.

**Comment by spirillen** [comment] 2022-01-17 20:52
This is not a pi-hole related issue, it clear that RFC:1952 never was designed to support IDNA domains, therefor they need to be converted, the same goes for DNS zones, there is no differ, if you should see otherwise in any web interface, it is related to translation.

**Comment by thomasmerz** [comment] 2022-01-20 15:09
PR #574 has already been merged - but PR #573 (which deals with some "spanish" IDNA domain(s)) is still open. Who can and will review and merge it? 🤔

**Comment by thomasmerz** [comment] 2022-02-20 22:19
Again, please close this issue, because it's done via both the linked PRs. Thank you 👍🏻

**Closed** 2022-02-25 16:51 UTC
Labels: Add Request

**Comment by spirillen** [comment] 2022-02-25 18:42
@thomasmerz why don't you just add the `closes https://github.com/blocklistproject/Lists/issues/605` to the commit text?? That would close the issue on merge

**Comment by thomasmerz** [comment] 2022-02-25 19:29
I didn't know this "closes" or "fixes" Feature in GitHub before🤷🏻‍♂️ Now I know 😁

**Comment by spirillen** [comment] 2022-02-25 19:53
Then you after all had a god day, you learned something new
