### ISSUE TITLE
[Add request] - trackital.checkposttt.top & other domains

### ISSUE THREAD

**Issue by Trainax** [blocklistproject/Lists#600] opened 2021-12-30 16:17 UTC
URL you wish to be added:
- `trackital.checkposttt.top`
- `corriertt.parceldlvr.xyz`
- `choicemonitor.top`
- `hellothere.shop` => See https://github.com/blocklistproject/Lists/issues/600#issuecomment-1003392878
- `jt2v.com`
- `loratech.pe`
- `aranu.ir`
- `realestatemashahir.ir`
- `conv-alida-recapiro-com.preview-domain.com`
- `ufesif.com`
- `disordsnltros.gifts`  => This is a domain I saw today in one of the Discord servers I moderate. It was spammed by a user in different channels on the server and the message said it was for free Nitro.

Why you believe this should be added: The domains which don't have a comment on the right are used to scam people with the "your package has been held" SMS scam. These domains were inside SMS messages which were sent to my friend or me.

Add to list: phishing

Other info you think we should know:

The SMS said (translated from Italian):

>Your package has been held at our shipping center.
>Please follow the instructions here:

**Comment by iam-py-test** [comment] 2021-12-30 16:23
@Trainax please provide specific urls.
The first redirects to Google even when I VPN to Italy or the US and the second one is blank

**Comment by Trainax** [comment] 2021-12-30 16:27
Here are the screenshots my friend made

The SMS he received

![pacco_trattenuto_1](https://user-images.githubusercontent.com/30187360/147769888-d0dbdaf8-48a1-4558-96ba-120d62ee121c.jpg)

After clicking the link in the SMS this page opened

![pacco_trattenuto_2](https://user-images.githubusercontent.com/30187360/147769878-960cf968-28fd-441d-9517-48d78927e3f2.jpg)

**Comment by iam-py-test** [comment] 2021-12-30 16:30
I got redirected to `hxxpx[:]//corriertt.parceldlvr[.]xyz/lmed/it/clstrack/?p=100&uclick=u3ftdu&uclickhash=u3ftdu-u3ftdu-k2-0-x9-fnwj-he6o-fa03b0`. Can you add that?
Also, I think, based on the url, that `avomas.me` might be some kind of url shortener.

**Comment by Trainax** [comment] 2021-12-30 16:38
> I got redirected to `hxxpx[:]//corriertt.parceldlvr[.]xyz/lmed/it/clstrack/?p=100&uclick=u3ftdu&uclickhash=u3ftdu-u3ftdu-k2-0-x9-fnwj-he6o-fa03b0`. Can you add that?

Sure, I will add it to my list in the first comment

> Also, I think, based on the url, that `avomas.me` might be some kind of url shortener.

It might be. I don't know. I inserted it in my first comment because I thought it was the website used specifically for this. I will remove it for now.

> The end was `https://choicemonitor.top/register/8p/cc/index.php?affiliate_id=30__&cid=61cb2b7d66619c0001abdb8a` but who knows? That could be legit

I have searched and found [this article in Italian](https://notizieh24.eu/sms-per-pacco-in-sospeso-da-ips-ma-e-un-tentativo-di-smishing/) which says that website is a smishing attempt, in the article screenshot there is what it looks like to be the same webpage but with a different domain, so I think the website I have linked earlier could also be the same thing

**Comment by iam-py-test** [comment] 2021-12-30 16:39
Yep, now that I look into it, it seems to be a trial version of a payment gateway hosted on the scammer's domain.
Thanks @Trainax

**Comment by Trainax** [comment] 2021-12-30 16:41
Do you think I should also add `choicemonitor.top` to my list in the first comment?

**Comment by iam-py-test** [comment] 2021-12-30 16:42
I think yes, but I'm no expert. 
I am working on reporting it for abuse so hope it will soon be down (though some abuse teams take months to reply)

**Comment by Trainax** [comment] 2021-12-30 16:46
I have added it to my add request list for now.

Thanks @iam-py-test and have a nice day!

**Comment by spirillen** [comment] 2021-12-30 21:41
Hey nice conversation you had... I come to think of phishing rather than scam, one of same, but phishing will request some personal info; So what would happen if you click the "monitora il tuo ordine" ?? will it start request information's?

**Comment by iam-py-test** [comment] 2021-12-30 22:16
> Hey nice conversation you had... I come to think of phishing rather than scam, one of same, but phishing will request some personal info; So what would happen if you click the "monitora il tuo ordine" ?? will it start request information's?

I think phishing is a type of scam, but I'm not sure
I just said scammer as "phisher" just sounds wrong to me. It does request information though (payment info)

**Comment by spirillen** [comment] 2021-12-30 23:17
Well according to the Old guy (the 90's) definition and Wikipedia then the sort version is for differences

**Scam** is trying to convince you to buy something that isn't real, like a car that do not exist.

**Phishing** it when they are disguising themself like a a nice car like a nice new BMW 7M while the car in fact is a old Fiat 500

The common is to hustle money, but in two different ways

| BMW | FIAT |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/44526987/147793760-b3e0a39e-218d-4f18-bd17-c68786f2c9a6.png) | ![image](https://user-images.githubusercontent.com/44526987/147793783-6121a525-b802-4fa9-b0ee-44e434d2d4aa.png) |

**Comment by Trainax** [comment] 2021-12-31 06:51
> So what would happen if you click the "monitora il tuo ordine"?

My friend said that after clicking the button a web page opened which showed the package was being held at the distribution center and the website was asking for money to unlock the package from the distribution center and allow the delivery.

Do you think I should modify my add request to add the domains to phishing list instead of scam?

**Comment by iam-py-test** [comment] 2021-12-31 13:04
The new domain seems dead:
![image](https://user-images.githubusercontent.com/84232764/147824894-58ba9bd4-e742-40a6-a616-3a4c9febb1ee.png)

**Comment by spirillen** [comment] 2021-12-31 14:28
@iam-py-test that is only a temporarily down message, I have added it to https://github.com/mitchellkrogza/phishing so I think it will be marked as suspected as phishing later by [cloudflare](https://mypdns.org/my-privacy-dns/matrix/-/issues/1794)

Thanks @Trainax for reporting these and spending the time to investigate this case, also a HUGE thanks to you friend for taking those awesome screenshots for documentation. It is for sure people like you who make our time well spend on maintaining thees blacklists no matter who's project it is.

Own note:
- https://mypdns.org/my-privacy-dns/matrix/-/issues/4154
- https://mypdns.org/my-privacy-dns/matrix/-/issues/4155
- https://mypdns.org/my-privacy-dns/matrix/-/issues/4156
- https://mypdns.org/my-privacy-dns/matrix/-/issues/4157
- https://mypdns.org/my-privacy-dns/matrix/-/issues/4158

**Comment by Trainax** [comment] 2021-12-31 14:46
I would like to add another domain. Yesterday I received a SMS telling me I have left some articles in the basket of an online shop I've never heard before and I think this is also phishing.

Here's the screenshot of the message I received.
![articoli_carrello](https://user-images.githubusercontent.com/30187360/147828870-223852fc-28bf-4475-8090-a4182da18f1d.jpg)

Translation:

> *My name with "OMG" at the end*, you have left some articles in the basket! *link*

**Comment by iam-py-test** [comment] 2021-12-31 14:57
Probably a phish too:
![image](https://user-images.githubusercontent.com/84232764/147829397-f5b4787d-09a6-4e84-81b1-2c8d753777f6.png)

**Comment by spirillen** [comment] 2021-12-31 15:24
> Probably a phish too: ![image](https://user-images.githubusercontent.com/84232764/147829397-f5b4787d-09a6-4e84-81b1-2c8d753777f6.png)

This that the end destination for above link @iam-py-test ? or is it an entirely new case?

**Comment by iam-py-test** [comment] 2021-12-31 15:47
Yep, dead
Maybe they are watching for references??

**Comment by spirillen** [comment] 2021-12-31 16:18
> Yep, dead

Should I understand this as you can't reproduce `choicemonitor.top`?


> Maybe they are watching for references??

Many of those phishing url only have a few shorts in them to avoid being detected / confirm, that's among the reason why my issue templates requires some proofs, and a screenshot is a powerful on :smirk: :wink:

**Comment by iam-py-test** [comment] 2021-12-31 16:20
I can't investigate further right now as I'm busy doing something else

**Comment by Trainax** [comment] 2022-01-01 08:48
Happy New Year everyone!

Since we are doing this I would like to also add other domains which were in other SMS I have received.

**First SMS**

![avviso_falso](https://user-images.githubusercontent.com/30187360/147846936-614fd459-c69d-42ab-92da-a09b0c92aab9.jpg)

Translation
> Second warning: *name*, we have tried to get in touch with you for your gift of AMAZON-PRIME. To request it follow this link: *link*

**Second SMS**

![immagine](https://user-images.githubusercontent.com/30187360/147847005-cadfa937-5e5d-46e5-a5a9-fc208d76c653.png)

Translation
> Shipment from DPDgroup in stock. To manage the redelivery: *link*

**Third SMS**

![immagine](https://user-images.githubusercontent.com/30187360/147847061-25a32ca2-8313-4393-8c61-985ac8cc6b47.png)

Translation
> Dear customer, we have just shipped your order n. Q769767. Track your shipment here: *link*

**Fourth SMS**

![pacco_restituito](https://user-images.githubusercontent.com/30187360/147847108-5de87f06-e51e-498c-87c6-f882f7aadc24.jpg)

Translation
> *My name*, your package will be returned! Last chance to confirm: *link*

**Fifth SMS**

![sms falso banca](https://user-images.githubusercontent.com/30187360/147847211-776dd05b-a192-4208-99c3-743d5ed59eb6.jpg)

This SMS pretends to be from a bank

Translation
> *Bank name*
> Dear customer, there is an anomaly with your bank account,
> we invite you to verify at the following link: *link*

**Sixth SMS**

![immagine](https://user-images.githubusercontent.com/30187360/147847223-d314eba7-a2c8-4110-8071-e221a6806daf.png)

Translation
> Your package has been held at our distribution center. Please follow the instructions here: *link*

**Comment by spirillen** [comment] 2022-01-01 11:12
Damned, Have been reconsidering a new phone number :open_mouth: 

Usually I would say each of these are a new issue (My politic) and I for sure embrace these reports non the less.

- `jt2v.com` (DEAD)

<details><summary>note to self (@spirillen)</summary>

referals:
  - `aranu.ir` (https://mypdns.org/my-privacy-dns/matrix/-/issues/4167)
  - `preview-domain.com` (https://mypdns.org/my-privacy-dns/matrix/-/issues/4168)
  - `ufesif.com` (https://mypdns.org/my-privacy-dns/matrix/-/issues/4169)
  - `loratech.pe` (https://mypdns.org/my-privacy-dns/matrix/-/issues/4170)
  - `realestatemashahir.ir` (https://mypdns.org/my-privacy-dns/matrix/-/issues/4171)

</details>

**Comment by Trainax** [comment] 2022-01-01 11:18
> Usually I would say each of these are a new issue (My politic) and I for sure embrace these reports non the less.

I too would consider opening one issue for each domain, however every domain except `hellothere.shop`, `conv-alida-recapiro-com.preview-domain.com`, `disordsnltros.gifts` and maybe `jt2v.com` are all about a package being held or similar so I thought about grouping them.

Do you think I shoud move those domains to a separate issue?

**Comment by iam-py-test** [comment] 2022-01-01 13:02
The second one just returned a 404 for me, but is detected by 3 engines: https://www.virustotal.com/gui/url/b45f9e872da1341bf0675e1d3666177b101e591c5ed5b35845159a01d3e54f4e
Third is also a 404 and VT clean
Four has been taken down and is detected by MS
Five returns a 404 but is detected by 4 engines: https://www.virustotal.com/gui/url/e1742ef8efd269542f57adfc1f81231518c757ffdf94aa3397631ce67786f4f6
Six is online and phishing, though detected by MS and two engines (https://www.virustotal.com/gui/url/7b6b75d77e0734f35b6c5ec4a94b21bb178ed5e6804f895089da848bb07f0531?nocache=1). Other domains include `italtrack.checkitemtt.top` and `choicemonitor.top`

**Comment by spirillen** [comment] 2022-01-01 14:27
> Do you think I should move those domains to a separate issue?

Next time :smile: Now it is done and as far I know, nodoby died

**Comment by spirillen** [comment] 2022-01-01 14:32
@iam-py-test 

first, second, third etc, could you right the domain/url instead, it become impossible to decode and follow your answer

And what was the real answer to `choicemonitor.top` is it a independent phishing domain that should be blacklisted as phishing or is it a innocent real payment gateway abused by scammers?

**Comment by iam-py-test** [comment] 2022-01-01 14:33
> @iam-py-test
> 
> first, second, third etc, could you right the domain/url instead, it become impossible to decode and follow your answer

I meant relating to the OP's comment https://github.com/blocklistproject/Lists/issues/600#issuecomment-1003527561
> And what was the real answer to `choicemonitor.top` is it a independent phishing domain that should be blacklisted as phishing or is it a innocent real payment gateway abused by scammers?

No idea. I reached out to the owners, but, due to New Years, I have revived no response.

**Comment by spirillen** [comment] 2022-01-01 18:07
Super, putting it on hold to you ping back

**Comment by Trainax** [comment] 2022-01-16 09:24
Hello everyone. Two weeks have gone by. Are there any updates on this?

Can we close this issue with a PR?

**Comment by iam-py-test** [comment] 2022-01-16 12:43
> Hello everyone. Two weeks have gone by. Are there any updates on this?
> 
> Can we close this issue with a PR?

It doesn't matter if @cryptogap @blocklistproject doesn't check this repo
@fishcharlie maybe you can handle it instead?

**Comment by fishcharlie** [comment] 2022-01-16 13:03
I'll look at this later today.

**Closed** 2022-01-17 00:07 UTC
Labels: Add Request

**Comment by iam-py-test** [comment] 2022-01-17 02:47
Thanks @fishcharlie
