### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by trackerct** [blocklistproject/Lists#833] opened 2022-09-27 08:28 UTC
Can you add blocklist please?
https://blocklistproject.github.io/Lists/tracking.txt

Trackers by Vivo Mobile (have a couple of dns queries)

tr-vcode-od.vivoglobal.com
tr-vcode-api.vivoglobal.com
tr-st-sl.vivoglobal.com
tr-domaincfg.vivoglobal.com
tr-timesync.vivoglobal.com
tr-romsp-unifyconfig.vivoglobal.com
asia-ex-adlog.vivoglobal.com
asia-analyzer-appstore.vivoglobal.com
asia-exstsdk.vivoglobal.com
asia-comort-stsdk.vivoglobal.com
asia-comonrt-stsdk.vivoglobal.com

Trackers by Vodafone

netperform-is.vodafone.com.tr
vodafonetr.sc.omtrdc.net
mplusps.ims.vodafone.com
mpluswf.ims.vodafone.com

Advertising
advertise.ldplayer.net
creative.eagllwin.com
api.eagllwin.com
storeen.ldmnq.com

Google Spyware (have a couple of dns queries)

telephonyspamprotect-pa.googleapis.com
growth-pa.googleapis.com
deviceintegritytokens-pa.googleapis.com
gmscompliance-pa.googleapis.com
mdh-pa.googleapis.com
firebaseinstallations.googleapis.com
digitalassetlinks.googleapis.com

**Comment by spirillen** [comment] 2022-09-29 14:53
duplicate of https://github.com/badmojr/1Hosts/issues/738#issuecomment-1259829616

**Comment by trackerct** [comment] 2022-10-12 16:40
co-vcode-api.vivoglobal.com
co-vcode-h5-od.vivoglobal.com
asia-vcode-or.vivoglobal.com
asia-exstatic.vivo.com
vcm-static.vivo.com
asia-commonitor-stsdk.vivoglobal.com
asia-romsp-unifyconfig.vivoglobal.com
asia-stp.vivoglobal.com
asia-vcode-api.vivoglobal.com

freegeoip.live
geocheck.sim-technik.de
ipapi.co
analytics.coollabs.io
statistic.live.126.net
m.equinoxplus.com
akamai.tiqcdn.com
app.anch.co
crash.uu.easebar.com
mobile.uu.easebar.com
uumov.fp.ps.easebar.com
uuov.fp.ps.easebar.com
uu.fp.ps.netease.com
mg.uu.163.com
adx.adsgaga.com
177657.tracking.hyros.com
ma1226-r.analytics.edgesuite.net
netperform-lz.vodafone.com
js-eu1.hscollectedforms.net
forms-eu1.hsforms.com
restapi.netmera.com
eturkcell.netmera.com
adiu.amap.com
alimelog.taobao.com
localization.services.pbs.org
cc-api-data.adobe.io
app-1c835e5474e6a378.mobileapi.usebutton.com
logs.us-east-1.amazonaws.com
vmweb-va.byteoversea.com
mcs-va.tiktok.com.edgekey.net
appad.cyberlink.com
abtest.tantanapp.com
report.tantanapp.com
client-tracking.tantanapp.com
sc-report.tantanapp.com
deviceid.tantanapp.com
counter.tantanapp.com
lorempixel.com
analytics-lal-nba.yinzcam.com
ads-lal-nba.yinzcam.com
api.adtech.etermax.com
gdpr-tcfv2.sp-prod.net
mynt-test-privacy.my.onetrust.com
analytics.meaww.com
vmweb-va.byteoversea.com
mssdk-va.tiktok.com
sf16-muse-va.ibytedtos.com
sotalcloud.blob.core.windows.net
xtrapath1.izatcloud.net
xtrapath2.izatcloud.net
xtrapath3.izatcloud.net
fl-badger-prod-statscluster.moonfroglabs.com
internetbrands-d.openx.net

**Comment by cryptogap** [comment] 2022-12-08 13:41
I will take a look into these

**Comment by cryptogap** [comment] 2023-01-08 01:19
Majority of these will be included in the next push

**Closed by cryptogap** 2023-01-08 01:19 UTC
Labels: Add Request
