### ISSUE TITLE
Why not provide an aggregated master list ?

### ISSUE THREAD

**Issue by nodje** [blocklistproject/Lists#168] opened 2021-01-14 14:54 UTC
Just stumbled upon your project while looking for good lists of domain to block.
And wondering why you wouldn't want to provide an aggregated list of all these specialized lists?

I mean it seems that any sensible user would have to take all of them or almost anyway.
A list or a command to grab them all and concatenate them in a place seem to be in order!

Or am I missing something on how this should be used?

**Comment by Trainax** [comment] 2021-01-14 15:03
Duplicate of #167

**Closed** 2021-01-15 14:16 UTC
