### ISSUE TITLE
[Add request] Adobe

### ISSUE THREAD

**Issue by PJGitHub9** [blocklistproject/Lists#862] opened 2022-12-02 20:15 UTC
Adobe Blocklist Project

https://github.com/PJGitHub9/PJsAdobeBlocklist

**Comment by blocklistproject** [comment] 2022-12-03 19:38
I have created this list but it is highly experimental until tested

**Comment by thomasmerz** [comment] 2022-12-14 22:11
Duplicate of issue #853

**Closed** 2022-12-17 22:44 UTC
Labels: Add Request
