### ISSUE TITLE
[Remove Request] Invalid domains

### ISSUE THREAD

**Issue by ndsvw** [blocklistproject/Lists#912] opened 2023-01-16 17:06 UTC
URL you wish to be removed:

 - pmenboeqhyrpvomq.v
 - pmenboeqhyrpvomq.w

When I updated PiHole, it listed them as invalid domains:

>   [i] Target: https://blocklistproject.github.io/Lists/abuse.txt
>   [✓] Status: Retrieval successful
>   [i] Analyzed 435182 domains, 2 domains invalid!
>       Sample of invalid domains:
>       - pmenboeqhyrpvomq.v
>       - pmenboeqhyrpvomq.w
>

**Comment by pawcoding** [comment] 2023-01-18 08:53
These two domains are also listed on the `malware` list. Of course, Pi-Hole issues the same error there.

**Comment by cryptogap** [comment] 2023-01-27 21:56
Duplicate of #921

**Closed** 2023-01-27 21:57 UTC
Labels: remove request
