### ISSUE TITLE
[Add request]

### ISSUE THREAD

**Issue by spradeep** [blocklistproject/Lists#850] opened 2022-11-07 08:05 UTC
URL you wish to be added: https://rajbet.com/user/registration?a_aid=Adcash&a_bid=9ddc79a7&data1=1667808195100010TINTV417314335674Vd

Why you believe this should be added: gambling

Add to list: gambling

Other info you think we should know:

**Comment by spirillen** [comment] 2022-11-07 14:28
Screenshot required / Spyware

![image](https://user-images.githubusercontent.com/44526987/200334863-eea63e74-620c-4693-8a90-7f7973590743.png)


![image](https://user-images.githubusercontent.com/44526987/200334796-6851b160-90cd-4116-8e98-764f2037569c.png)

**Comment by spradeep** [comment] 2022-11-07 14:40
![image](https://user-images.githubusercontent.com/411231/200337445-0b48fad5-705d-4849-a465-cf6f2b185508.png)
SS added

**Comment by spirillen** [comment] 2022-11-07 14:53
Thanks for helping [mypdns.org](https://mypdns.org/my-privacy-dns/matrix/-/issues/1167634) by getting this domain confirmed as gambling

**Comment by thomasmerz** [comment] 2022-12-14 21:58
Duplicate of issue #767

**Closed** 2023-01-02 03:19 UTC
Labels: Add Request
